### ISSUE TITLE
client setzt beim überflashen falsche hna und iptables regeln

### ISSUE THREAD

**Issue by storchi** [weimarnetz/registrator-nodejs#11]
und überhaupt. für was war der registrator gedacht? macht er das?
nur mal so
cs

**Comment by andibraeu** [comment]
der registrator macht was er soll.. Mitteilen, ob eine Knotennummer vergeben ist und eine neue Nummer vorschlagen, wenn sie schon vergeben ist.

Das Problem liegt hier beim Client, der die neue Nummer nicht richtig verarbeitet und in Folge dessen etwas falsch macht. Die Fehlerbehebung muss aber im Firmwarerepo geschehen: https://github.com/weimarnetz/weimarnetz/issues/46
