### ISSUE TITLE
registering new node number from client

### ISSUE THREAD

**Issue by andibraeu** [weimarnetz/registrator-nodejs#5]
now it's like that:
- if a router tries to register an existing node, the registrator client rejects the query
- then the client does an apply_profile.code, but doesn't get a new node number
- so the client tries it every hour

case:
- if client doesn't have a node number, registrator should give it to the client

special cases:
- a clients has been reset without keeping anything. so we have an existing node number with an existing mac address, but the client tells another ssh pubkey

**Comment by eins78** [comment]
this is not an issue with the API, but with the clients using it.
will add a 'getNumber' method to the jquery-client, though, to make that more clear…

**Comment by eins78** [comment]
I found the shell script inside the firmware I was talking about all the time.
So this seems to be the 'official' client: https://github.com/bittorf/kalua/blob/master/openwrt-addons/usr/sbin/cron.registrator_client.sh
Maybe it is not even used, but you should be faster than me in finding out.

Edit: this file in weimarnetz/weimarnetz: https://github.com/weimarnetz/weimarnetz/blob/master/openwrt-addons/usr/sbin/cron.registrator_client.sh

**Comment by andibraeu** [comment]
> I found the shell script inside the firmware I was talking about all
> the time.
> So this seems to be the 'official' client:
> https://github.com/bittorf/kalua/blob/master/openwrt-addons/usr/sbin/cron.registrator_client.sh
> Maybe it is not even used, but you should be faster than me in finding
> out.

we aren't in sync with bittorf/kalua, but our official client looks
nearly the same:
https://github.com/weimarnetz/weimarnetz/blob/master/openwrt-addons/usr/sbin/cron.registrator_client.sh

maybe we could enhance that script by the new feature of the registrator

**Comment by eins78** [comment]
I am starting by commenting the script…

**Comment by andibraeu** [comment]
Am Freitag, den 14.02.2014, 12:12 -0800 schrieb Max Albrecht:

> I am starting by commenting the script…

very nice! :-)

btw: http://reg.weimarnetz.de/static/jquery-client-test.html

**Comment by eins78** [comment]
so, to summarize the mailing list and short IRL discussion from last tuesday:
1. actually everything works how we want, but we should check the client implementation(s) — started here: weimarnetz/weimarnetz#29
2. the 'special case' (dev kit router reset without backup but still keep number) can be solved by a password-reset — TBD, duplicate of eins78/registrator#1 :neckbeard:
