### ISSUE TITLE
init script throws error

### ISSUE THREAD

**Issue by andibraeu** [weimarnetz/registrator-nodejs#9]
new misc/registrator script throws following error:

dirname: zusätzlicher Operand „-o“
„dirname --help“ gibt weitere Informationen.
Starting node.js weimarnetz registrator: registrator  --->  started node.js weimarnetz registrator: registratorstart-stop-daemon: unable to chdir() to --make-pidfile (No such file or directory)
.

**Comment by eins78** [comment]
Just revert my small change and wait till Debian is finished throwing out their fucking ridiculous init "system".

**Comment by L337hium** [comment]
WORKDIR=`dirname $( echo $DAEMON_ARGS | awk '{print $1}' )`

**Comment by eins78** [comment]
@L337hium I don't understand what you're trying to say. 
But I also don't understand how adding an argument to `DAEMON_ARGS` would brake anything. 

Feel free to add a fix, I won't since I am using `systemd`.

**Comment by andibraeu** [comment]
I'll use the old version of init script, the only disadvantage is there's no PID file saved, so stopping the service doesn't work. you have to kill the process manually
